#!/bin/bash

filename=$1

while read line; do
    n=$line
    factors=""
    for ((i=2; i<=n/2; i++)); do
        if ((n % i == 0)); then
            factors="$factors $i"
        fi
    done
    echo "$n = $factors"
done < $filename
