#!/bin/bash

filename=$1

while read line; do
    n=$line
    factors=""
    count=0
    for ((i=1; i<=n; i++)); do
        if ((n % i == 0)); then
            factors="$factors $i"
            ((count++))
            if [ $count -eq 2 ]
            then
                break
            fi
        fi
    done
    echo "$n = $factors"
done < $filename

