#!/bin/bash

# Function to find factors of a number
find_factors() {
    local n=$1
    for i in $(seq 2 $(isqrt $n)); do
        if [[ $(($n % $i)) -eq 0 ]]; then
            echo "$i $(($n/$i))"
            break
        fi
    done
}

# Function to calculate the integer square root of a number
isqrt() {
    local n=$1
    echo "scale=0;(sqrt($n)+0.5)/1" | bc
}

# Check if input file is provided
if [ -z "$1" ]; then
    echo "Please provide an input file as an argument"
    exit 1
fi

# Read numbers from input file and find factors
while read n; do
    factors=($(find_factors $n))
    echo "$n=${factors[0]}*${factors[1]}"
done < $1

