#!/bin/bash

factorize() {
    local n=$1
    for ((i=2; i<=n/2; i++)); do
        if [ $(($n%i)) -eq 0 ]; then
            echo "$((n/i))*$i"
            return 0
        fi
    done
    echo "$n * 1"
}

if [ $# -ne 1 ]; then
    echo "Usage: $0 <file>"
    exit 1
fi

while read n; do
    echo "$n=$(factorize $n)"
done < $1
